version: 2.1

commands: # a reusable command with parameters
  set_deploydir:
    parameters:
      deploy_dir:
        default: "./infrastructure"
        type: string
    steps:
      - run:
          command: |
            export DEPLOY_DIR=<<parameters.deploy_dir>>
            echo "Deploy_dir':' $DEPLOY_DIR"

deploy-without-test: &deploy-without-test
  docker:
    - image: cimg/base:stable
  steps:
    - run:
        name: "deploy"
        command: |
          echo "Deploy_dir $DEPLOY_DIR"

jobs:
  # BoxOs jobs
  deploy-dev:
    <<: *deploy-without-test
    environment:
      SDLC: dev
      K8S_TARGET: boxos
      DEPLOY_DIR: ./infrastructure
  deploy-qastg:
    <<: *deploy-without-test
    environment:
      SDLC: qastg
      K8S_TARGET: boxos
      DEPLOY_DIR: ./infrastructure


  # Eks jobs
  eks-deploy-dev:
    <<: *deploy-without-test
    environment:
      SDLC: dev
      K8S_TARGET: eks
  eks-deploy-qastg:
    <<: *deploy-without-test
    environment:
      SDLC: qastg
      K8S_TARGET: eks

workflows:
  # BoxOs workflows
  build-boxos:
    jobs:
      - deploy-dev
      - deploy-qastg

  # EKS workdflows
  build-eks:
    jobs:
      - eks-deploy-dev
      - eks-deploy-qastg
