version: 2.1

commands: # a reusable command with parameters
  set_deploydir:
    parameters:
      deploy_dir:
        default: "./infrastructure"
        type: string
    steps:
      - run:
          command: |
            DEPLOY_DIR=<<parameters.deploy_dir>>
            echo "Deploy_dir':' $DEPLOY_DIR"

jobs:
  test-eks:
    docker:
      - image: cimg/base:stable
    environment:
      - K8S_TARGET: eks
      - DEPLOY_DIR: ./infrastructure-eks
    steps:
      - checkout
      - run:
          name: "test-eks"
          command: echo "Deploy_dir':' $DEPLOY_DIR"
  test-boxos:
    docker:
      - image: cimg/base:stable
    environment:
      - K8S_TARGET: BoxOs
      - DEPLOY_DIR: ./infrastructure
    steps:
      - checkout
      - run:
          name: "test-boxos"
          command: echo "Deploy_dir':' $DEPLOY_DIR"


workflows:
  build-eks:
    jobs:
      - test-eks
  build-boxos:
    jobs:
      - test-boxos
